- name: install python and pip
  apt:
    name: ['python-pip', 'python-dev']
    state: present

- name: upgrade pip
  command: "pip install --upgrade pip"

- name: install setuptools with pip
  pip:
    name: setuptools
    state: present
    extra_args: -U

